# ============================================================
# Diccionario básico español -> inglés para el buscador.
# Cobertura: vocabulario típico de IA/ML, salud, estadística y
# los temas presentes en el corpus. No es una traducción completa
# ni gramatical -- es una sustitución de frases/palabras clave,
# suficiente para que una consulta en español "aterrice" cerca del
# vocabulario en inglés del corpus (que es 100% inglés).
# Las claves NO llevan tildes (se normalizan antes de comparar).
# ============================================================

dic_es_en <- c(
  # Frases (más específicas primero, se aplican antes que palabras sueltas)
  "inteligencia artificial generativa"   = "generative artificial intelligence",
  "inteligencia artificial"              = "artificial intelligence",
  "aprendizaje automatico"               = "machine learning",
  "aprendizaje profundo"                 = "deep learning",
  "aprendizaje supervisado"              = "supervised learning",
  "aprendizaje no supervisado"           = "unsupervised learning",
  "aprendizaje por refuerzo"             = "reinforcement learning",
  "red neuronal"                         = "neural network",
  "redes neuronales"                     = "neural networks",
  "redes neuronales convolucionales"     = "convolutional neural networks",
  "procesamiento de lenguaje natural"    = "natural language processing",
  "vision por computador"                = "computer vision",
  "vision artificial"                    = "computer vision",
  "modelo de lenguaje grande"            = "large language model",
  "modelos de lenguaje grandes"          = "large language models",
  "generacion de texto"                  = "text generation",
  "generacion de imagenes"               = "image generation",
  "arbol de decision"                    = "decision tree",
  "bosque aleatorio"                     = "random forest",
  "maquina de vectores de soporte"       = "support vector machine",
  "reduccion de dimensionalidad"         = "dimensionality reduction",
  "extraccion de caracteristicas"        = "feature extraction",
  "deteccion de objetos"                 = "object detection",
  "vision por computadora"               = "computer vision",
  "analisis de sentimientos"             = "sentiment analysis",
  "mineria de datos"                     = "data mining",
  "ciencia de datos"                     = "data science",
  "series temporales"                    = "time series",
  "series de tiempo"                     = "time series",
  "datos faltantes"                      = "missing data",
  "calidad del aire"                     = "air quality",
  "monitoreo ambiental"                  = "environmental monitoring",
  "sistema de recomendacion"             = "recommendation system",
  "sistemas de recomendacion"            = "recommendation systems",
  "comercio electronico"                 = "e-commerce",
  "compras en linea"                     = "online shopping",
  "imagenes medicas"                     = "medical imaging",
  "imagen medica"                        = "medical image",
  "atencion medica"                      = "healthcare",
  "cuidado de la salud"                  = "healthcare",
  "ensayo clinico"                       = "clinical trial",
  "ensayos clinicos"                     = "clinical trials",
  "historia clinica"                     = "medical record",
  "resonancia magnetica"                 = "MRI",
  "tomografia computarizada"             = "CT scan",
  "prediccion de riesgo"                 = "risk prediction",
  "cancer de piel"                       = "skin cancer",
  "cancer de pulmon"                     = "lung cancer",
  "enfermedades cardiovasculares"        = "cardiovascular diseases",
  "valor p"                              = "p-value",
  "regresion bayesiana"                  = "bayesian regression",
  "modelo predictivo"                    = "predictive model",
  "modelos predictivos"                  = "predictive models",

  # Palabras sueltas
  "inteligencia"      = "intelligence",
  "artificial"        = "artificial",
  "generativa"        = "generative",
  "generativo"        = "generative",
  "aprendizaje"       = "learning",
  "automatico"        = "automatic",
  "profundo"          = "deep",
  "clasificacion"     = "classification",
  "clasificador"      = "classifier",
  "regresion"         = "regression",
  "agrupamiento"      = "clustering",
  "segmentacion"      = "segmentation",
  "transformador"     = "transformer",
  "sobreajuste"       = "overfitting",
  "algoritmo"         = "algorithm",
  "algoritmos"        = "algorithms",
  "modelo"            = "model",
  "modelos"           = "models",
  "prediccion"        = "prediction",
  "predictivo"        = "predictive",
  "diagnostico"       = "diagnosis",
  "diagnosticar"      = "diagnose",
  "enfermedad"        = "disease",
  "enfermedades"      = "diseases",
  "cancer"            = "cancer",
  "paciente"          = "patient",
  "pacientes"         = "patients",
  "tratamiento"       = "treatment",
  "salud"             = "health",
  "medico"            = "medical",
  "medica"            = "medical",
  "clinico"           = "clinical",
  "clinica"           = "clinical",
  "radiografia"       = "x-ray",
  "pandemia"          = "pandemic",
  "estadistica"       = "statistics",
  "estadistico"       = "statistical",
  "hipotesis"         = "hypothesis",
  "correlacion"       = "correlation",
  "varianza"          = "variance",
  "distribucion"      = "distribution",
  "muestreo"          = "sampling",
  "probabilidad"      = "probability",
  "bayesiano"         = "bayesian",
  "imputacion"        = "imputation",
  "ambiental"         = "environmental",
  "monitoreo"         = "monitoring",
  "recomendacion"     = "recommendation",
  "sentimientos"      = "sentiment",
  "texto"             = "text",
  "imagenes"          = "images",
  "imagen"            = "image",
  "aplicaciones"      = "applications",
  "aplicacion"        = "application",
  "sistemas"          = "systems",
  "sistema"           = "system",
  "datos"             = "data",
  "analisis"          = "analysis",
  "tecnicas"          = "techniques",
  "tecnica"           = "technique",
  "metodos"           = "methods",
  "metodo"            = "method",
  "nuevo"             = "new",
  "nueva"             = "new",
  "riesgo"            = "risk",
  "deteccion"         = "detection",
  "clasificar"        = "classify",
  "identificar"       = "identify",
  "prediciendo"       = "predicting",
  "prediciendo"       = "predicting"
)
